name: Create Pull Request
on:
  push

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: commit
        run: echo "::set-output name=sha::${{ github.sha }}"

      - name: Determine commit range
        id: commit_range
        run: echo "::set-output name=range::${{ github.event.before }}..${{ github.event.after }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.pull_request}}
          branch: develop2
          title: Automatically created pull request
          body: Changes from the develop branch
          base: develop
          head: develop
          commit: ${{ steps.commit.outputs.sha }}
          commit-range: ${{ steps.commit_range.outputs.range }}
