name: Staging Auto-PR
on:
  push:
    branches: [develop3,master]

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - name: Get Commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::${GITHUB_SHA}"
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "develop2"
        pr_title: "Pulling ${{ github.ref }} into develop2 "
        pr_body: "*An automated PR*"
        pr_reviewer: "jimbou"
        pr_draft: true
